# Type stubs for the compiled C++ module memory_graph_core
# Generated automatically - do not edit manually

from typing import Any, Dict, List, Set, Tuple, Union

class EdgeType:
    SYMMETRIC: int
    ASYMMETRIC: int

SymmetricConnections = Set[str]
AsymmetricConnections = Tuple[str, str]

class Node:
    def __init__(self, id: str, label: str, metadata: Dict[str, Any] = ...) -> None: ...
    def get_id(self) -> str: ...
    def get_label(self) -> str: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def get_connections(self) -> List[str]: ...
    def set_label(self, label: str) -> None: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> Node: ...

class Edge:
    def __init__(
        self,
        id: str,
        label: str,
        type: int,
        connections: Union[Set[str], tuple[str, str]],
        weight: float = 1.0,
        metadata: Dict[str, Any] = ...,
    ) -> None: ...
    def get_id(self) -> str: ...
    def get_label(self) -> str: ...
    def get_type(self) -> int: ...
    def get_connections(self) -> Union[Set[str], tuple[str, str]]: ...
    def get_weight(self) -> float: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def is_group_edge(self) -> bool: ...
    def set_label(self, label: str) -> None: ...
    def set_weight(self, weight: float) -> None: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> Edge: ...

class MemoryGraph:
    def __init__(self, metadata: Dict[str, Any] = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def has_node(self, node_id: str) -> bool: ...
    def get_node(self, node_id: str) -> Node: ...
    def remove_node(self, node_id: str) -> None: ...
    def get_nodes(self) -> List[Node]: ...
    def add_edge(self, edge: Edge) -> None: ...
    def add_group_edge(
        self,
        id: str,
        label: str,
        node_ids: Set[str],
        weight: float = 1.0,
        metadata: Dict[str, Any] = ...,
    ) -> None: ...
    def has_edge(self, edge_id: str) -> bool: ...
    def get_edge(self, edge_id: str) -> Edge: ...
    def remove_edge(self, edge_id: str) -> None: ...
    def get_edges(self) -> List[Edge]: ...
    def get_group_edges(self) -> List[Edge]: ...
    def get_group_members(self, group_id: str) -> Set[str]: ...
    def get_neighbors(self, node_id: str) -> List[Node]: ...
    def query(
        self, node_id: str, max_depth: int = 1, min_weight: float = 0.0
    ) -> Dict[str, Any]: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> MemoryGraph: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def __len__(self) -> int: ...
