# Type stubs for the compiled C++ module memory_graph_core
# Generated automatically - do not edit manually

from typing import Any, Dict, List, Set, Tuple, Union, Callable

class EdgeType:
    SYMMETRIC: int
    ASYMMETRIC: int

SymmetricConnections = Set[str]
AsymmetricConnections = Tuple[str, str]

class Node:
    def __init__(self, id: str, label: str, metadata: Dict[str, Any] = ...) -> None: ...
    def get_id(self) -> str: ...
    def get_label(self) -> str: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def get_connections(self) -> List[str]: ...
    def set_label(self, label: str) -> None: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> Node: ...

class Edge:
    def __init__(
        self,
        id: str,
        label: str,
        type: int,
        connections: Union[Set[str], tuple[str, str]],
        weight: float = 1.0,
        metadata: Dict[str, Any] = ...,
    ) -> None: ...
    def get_id(self) -> str: ...
    def get_label(self) -> str: ...
    def get_type(self) -> int: ...
    def get_connections(self) -> Union[Set[str], tuple[str, str]]: ...
    def get_weight(self) -> float: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def is_group_edge(self) -> bool: ...
    def set_label(self, label: str) -> None: ...
    def set_weight(self, weight: float) -> None: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> Edge: ...

class MemoryGraph:
    def __init__(self, metadata: Dict[str, Any] = ...) -> None: ...
    def add_node(self, node: Node) -> None: ...
    def has_node(self, node_id: str) -> bool: ...
    def get_node(self, node_id: str) -> Node: ...
    def remove_node(self, node_id: str) -> None: ...
    def get_nodes(self) -> List[Node]: ...
    def add_edge(self, edge: Edge) -> None: ...
    def add_group_edge(
        self,
        id: str,
        label: str,
        node_ids: Set[str],
        weight: float = 1.0,
        metadata: Dict[str, Any] = ...,
    ) -> None: ...
    def has_edge(self, edge_id: str) -> bool: ...
    def get_edge(self, edge_id: str) -> Edge: ...
    def remove_edge(self, edge_id: str) -> None: ...
    def get_edges(self) -> List[Edge]: ...
    def get_group_edges(self) -> List[Edge]: ...
    def get_group_members(self, group_id: str) -> Set[str]: ...
    def get_neighbors(self, node_id: str) -> List[Node]: ...
    def query(
        self, node_id: str, max_depth: int = 1, min_weight: float = 0.0
    ) -> Dict[str, Any]: ...
    def to_json(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_json(data: Dict[str, Any]) -> MemoryGraph: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def set_metadata(self, metadata: Dict[str, Any]) -> None: ...
    def update_metadata(self, key: str, value: Any) -> None: ...
    def __len__(self) -> int: ...

# Traversal Functions
def bfs(graph: MemoryGraph, start: str, max_depth: int = -1) -> List[str]:
    """Breadth-First Search traversal starting from a node."""
    ...

def dfs(graph: MemoryGraph, start: str, max_depth: int = -1) -> List[str]:
    """Depth-First Search traversal starting from a node."""
    ...

def shortest_path(graph: MemoryGraph, from_node: str, to_node: str) -> List[str]:
    """Find the shortest path between two nodes."""
    ...

def find_all_paths(
    graph: MemoryGraph, from_node: str, to_node: str, max_depth: int = -1
) -> List[List[str]]:
    """Find all paths between two nodes."""
    ...

def has_cycle(graph: MemoryGraph) -> bool:
    """Check if the graph contains a cycle."""
    ...

def topological_sort(graph: MemoryGraph) -> List[str]:
    """Perform topological sort on a directed acyclic graph."""
    ...

def is_connected(graph: MemoryGraph, start: str) -> bool:
    """Check if graph is connected from a given start node."""
    ...

def subgraph(
    graph: MemoryGraph, center: str, radius: int, include_edges: bool = True
) -> MemoryGraph:
    """Extract a subgraph centered at a node within a radius."""
    ...

def subgraph_by_predicate(
    graph: MemoryGraph,
    predicate: Callable[[Node], bool],
    include_neighbors: bool = False,
) -> MemoryGraph:
    """Extract a subgraph containing all nodes matching a predicate."""
    ...

def find_nodes_by_label(graph: MemoryGraph, label: str) -> List[str]:
    """Find nodes by label."""
    ...

def find_nodes_by_metadata(graph: MemoryGraph, key: str, value: Any) -> List[str]:
    """Find nodes by metadata key-value pair."""
    ...

def get_context_window(
    graph: MemoryGraph, center: str, max_tokens: int = 4096, min_relevance: float = 0.5
) -> Dict[str, Any]:
    """Get a context window for an LLM."""
    ...

# Serialization Functions
class CompressionType:
    NONE: int
    ZLIB: int
    LZ4: int

class SerializationOptions:
    include_metadata: bool
    include_edges: bool
    compression: int
    version: int
    def __init__(self) -> None: ...

def to_binary(graph: MemoryGraph, options: SerializationOptions = ...) -> bytes:
    """Serialize a MemoryGraph to binary format."""
    ...

def from_binary(data: bytes) -> MemoryGraph:
    """Deserialize a MemoryGraph from binary format."""
    ...

def compute_delta(before: MemoryGraph, after: MemoryGraph) -> Dict[str, Any]:
    """Compute the difference between two graphs."""
    ...

def apply_delta(graph: MemoryGraph, delta: Dict[str, Any]) -> None:
    """Apply a delta to a graph."""
    ...

def apply_delta_binary(graph: MemoryGraph, delta_data: bytes) -> None:
    """Apply a delta from binary format."""
    ...

def compress(data: bytes, type: int = ...) -> bytes:
    """Compress binary data."""
    ...

def decompress(data: bytes) -> bytes:
    """Decompress binary data."""
    ...

def get_version(data: bytes) -> int:
    """Get the serialization version from binary data."""
    ...

def is_valid_format(data: bytes) -> bool:
    """Check if binary data is valid for this version."""
    ...
