# python/src/memory_agent/core/schemas.py
# Pydantic Validation Schemas: contracts between the agent and LLM

from pydantic import BaseModel, Field
from typing import Any, Literal, Type

from .types import Entity, Relation, ComprehensionResult, KnowledgeDelta


class EntitySchema(BaseModel):
    """Schema for entity extraction. (No ID required; auto-generated by DTO)."""

    label: str = Field(..., description="Human-readable label of the entity")
    type: str | None = Field(
        None, description="Entity type (e.g., person, location, concept)"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence score"
    )

    def to_entity(self) -> "Entity":
        from .types import Entity

        return Entity(
            label=self.label,
            type=self.type,
            confidence=self.confidence,
            metadata=self.metadata,
        )


class RelationSchema(BaseModel):
    """Schema for relation extraction. (Uses labels for source/target; normalized by DTO)."""

    source_label: str = Field(..., description="Label of the source entity")
    target_label: str = Field(..., description="Label of the target entity")
    label: str = Field(..., description="Relation label (e.g., loves, located_in)")
    direction: Literal["symmetric", "asymmetric"] = Field(
        "asymmetric", description="Directionality"
    )
    weight: float = Field(default=0.5, ge=0.0, le=1.0, description="Relation weight")
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Confidence score"
    )

    def to_relation(self) -> "Relation":
        from .types import Relation

        return Relation(
            source_label=self.source_label,
            target_label=self.target_label,
            label=self.label,
            direction=self.direction,
            weight=self.weight,
            confidence=self.confidence,
        )


class ComprehensionSchema(BaseModel):
    """Schema for comprehension output."""

    goal: str = Field(..., description="the end goal assimilated from the user query")
    plan: list[str] = Field(
        default_factory=list, description="Step-by-step plan to solve the query"
    )
    user_intent: str = Field(..., description="User intent (e.g., ask, clarify, build)")
    modus_operandi: Literal["REACT", "COGITO"] = Field(
        default="REACT", description="Agent operation mode"
    )
    active_context: str = Field(
        ...,
        description="Context classification (e.g., question_answering, lore_building)",
    )
    entities: list[EntitySchema] = Field(
        default_factory=list, description="Extracted entities"
    )
    relations: list[RelationSchema] = Field(
        default_factory=list, description="Extracted relations"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Overall confidence"
    )

    def to_comprehension_result(self) -> "ComprehensionResult":
        from .types import ComprehensionResult

        return ComprehensionResult(
            goal=self.goal,
            plan=self.plan,
            intent=self.user_intent,
            path=self.modus_operandi,
            context=self.active_context,
            entities=[e.to_entity() for e in self.entities],
            relations=[r.to_relation() for r in self.relations],
            confidence=self.confidence,
        )


class ConsolidationSchema(BaseModel):
    """Schema for consolidation output. Maps directly to KnowledgeDelta."""

    knowledge_summary: str = Field(
        default="", description="Summary of current knowledge"
    )
    new_entities: list[EntitySchema] = Field(
        default_factory=list, description="New entities to add"
    )
    new_relations: list[RelationSchema] = Field(
        default_factory=list, description="New relations to add"
    )
    modified_entities: list[EntitySchema] = Field(
        default_factory=list, description="Modified entities"
    )
    modified_relations: list[RelationSchema] = Field(
        default_factory=list, description="Modified relations"
    )
    gaps: list[str] = Field(
        default_factory=list,
        description="Missing information (simple string questions)",
    )
    conflicts: list[dict[str, Any]] = Field(
        default_factory=list, description="Knowledge conflicts"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0, description="Consolidation confidence"
    )

    def to_knowledge_delta(self) -> "KnowledgeDelta":
        """Convert to KnowledgeDelta via DTOs (ensures validation)."""
        from .types import KnowledgeDelta

        return KnowledgeDelta(
            new_entities=[e.to_entity() for e in self.new_entities],
            new_relations=[r.to_relation() for r in self.new_relations],
            modified_entities=[e.to_entity() for e in self.modified_entities],
            modified_relations=[r.to_relation() for r in self.modified_relations],
            gaps=self.gaps,
            conflicts=self.conflicts,
            confidence=self.confidence,
            source="llm_consolidation",
        )


def get_json_schema(model: Type[BaseModel]) -> dict[str, Any]:
    """
    Get JSON schema for a Pydantic mode.
    (this is used by LLM providers that support structured output via schema)
    """
    return model.model_json_schema()


def get_llm_format_instructions(model: Type[BaseModel]) -> str:
    """
    Generate Human-readable format instructions for LLM prompts.
    (this creates instructions that tell the LLM exactly what JSON structure to return)
    """
    schema = get_json_schema(model)
    properties = schema.get("properties", {})
    required = schema.get("required", [])

    lines = ["Return a JSON object with the following structure:"]
    lines.append("{")

    for prop_name, prop_info in properties.items():
        required_marker = " (required)" if prop_name in required else " (optional)"
        prop_type = prop_info.get("type", "any")
        description = prop_info.get("description", "")

        # Hanle nested objects:
        if prop_type == "array":
            items = prop_info.get("items", {})
            item_type = items.get("type", "any")
            lines.append(
                f' "{prop_name}": [{{ ... }}]  # {description} (array of {item_type}){required_marker}'
            )
        elif prop_type == "object":
            lines.append(f' "{prop_name}": {{ ... }}  # {description}{required_marker}')
        else:
            lines.append(
                f' "{prop_name}": <{prop_type}>  # {description}{required_marker}'
            )

    lines.append("}")
    lines.append("")
    lines.append("Rules:")
    lines.append("1. Return ONLY valid JSON - no explanations, markdown, or extra text")
    lines.append("2. Include all required fields")
    lines.append("3. Use proper types (strings in quotes, booleans as true/false)")
    lines.append("4. No trailing commas")
    lines.append("5. If you cannot provide a value, use null or omit optional fields")

    return "\n".join(lines)
